CC = cc
CFLAGS = -Wall -Wextra -Werror
MODULES = ft_file.c ft_format.c ft_ntoname.c ft_strlen.c ft_todict.c main.c
OUT = rush-02

all: rush02

rush02:
	$(CC) $(CFLAGS) $(MODULES) -o $(OUT)

fclean:
	rm -f rush-02